server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.154.199
    username: admin
    password: admin
    port: 5672
    virtual-host: /admin
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://192.168.154.199:2181
  protocol:
    port: -1
  provider:
    timeout: 5000
  #当前服务作为消费者，不检查提供者是否启动
  #consumer:
    #check: false