server:
  port: 8084
spring:
  data:
    solr:
      host: http://192.168.154.199:8080/solr
dubbo:
  application:
    name: search_service
  registry:
    address: zookeeper://192.168.154.199:2181
  protocol:
    port: -1
    name: dubbo