server:
  port: 8087
spring:
  datasource:
    url:  jdbc:mysql:///shop
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.154.199:2181
  protocol:
    port: -1
  provider:
    timeout: 10000