spring:
  thymeleaf:
    cache: false
server:
  port: 8080
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.154.199:2181
  consumer:
    timeout: 5000
#配置fdfs
fdfs:
  tracker-list: 192.168.154.199:22122
  thumb-image:
    width: 100
    height: 100
  pool:
    jmx-enabled: false
  serverpath: http://192.168.154.199/